# Generated by Django 4.0.8 on 2026-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sample_a1_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='explanation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
