# Generated by Django 4.0.8 on 2026-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testquestion_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='C1', max_length=2),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
